services:
  jaeger:
    image: jaegertracing/all-in-one:1.51.0
    restart: always
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"    # OTLP HTTP endpoint for OTEL Collector
      - "14250:14250"  # Jaeger gRPC collector
    environment:
      COLLECTOR_OTLP_ENABLED: "true"

  otel-collector:
    image: otel/opentelemetry-collector:0.90.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-trace-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver from EMQX
      - "13133:13133" # Health check
    depends_on:
      - jaeger

  emqx:
    image: emqx/emqx-enterprise:6.0.0
    container_name: emqx
    restart: unless-stopped
    volumes:
      - emqx_data:/opt/emqx/data
      - ./base.hocon:/opt/emqx/etc/base.hocon:ro
    ports:
      - "1883:1883"    # MQTT
      - "18083:18083"  # EMQX Dashboard
    depends_on:
      - otel-collector

volumes:
  emqx_data:
